name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: copy google-service
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

    - name: generate gradlew
      run: gradle wrapper

    - name: unit test
      run: ./gradlew testDebugUnitTest

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
