name: Run Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: copy google-service
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

    - name: generate gradlew
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: unit test
      run: ./gradlew testDebugUnitTest

    - name: assembleDebug
      run: ./gradlew assembleDebug --stacktrace

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Run Instrumentation Tests in Firebase Test Lab
      run: >
        gcloud firebase test android run
        --type robo
        --app app/build/outputs/apk/debug/app-debug.apk
        --device model=flame,version=29,locale=ja,orientation=landscape
        --async
        --timeout 90s

